In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.decomposition import PCA
from unidecode import unidecode
from tqdm import tqdm
import matplotlib.pyplot as plt

c:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\__init__.py:82: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.5.3)
  import scipy.linalg  # noqa

In [4]:
def build_stats(filename_full='stats_full', filename_reduced='stats_reduced'):
    df = pd.read_csv('unified_player_stats.csv')
    df = df.loc[df['season'] == "2025-26"]
    df = df[['player', '_name_norm', 'team', 'pos', 'games', 'minutes', 'ninety_s', 'shots_per90', 'shots_on_target', 'shots_inside_box', 'shots_outside_box', 'npxg_per90', 'npxg_overperformance', 'goal_conversion_pct', 'big_chances_missed', 'key_passes_per90', 'xag_per90', 'attempt_assists', 'big_chances_created_per90', 'xg_chain_per90', 'xg_buildup_per90', 'pass_to_assist', 'passes_total', 'pass_completion_pct', 'passes_final_third', 'passes_opp_half', 'long_balls_total', 'long_balls_pct', 'crosses_total', 'crosses_pct', 'chipped_passes_total', 'chipped_passes_pct', 'touches', 'dribbles_per90', 'dribbles_pct', 'dispossessed', 'possession_lost', 'ball_recoveries', 'possession_won_att_third', 'tackles', 'tackles_won_pct', 'interceptions_per90', 'clearances', 'blocked_shots', 'dribbled_past', 'aerials_won_pct', 'ground_duels_won_pct', 'duels_won_pct', 'fouls', 'fouled']]
    df['shots_on_target_per90'] = df['shots_on_target']/df['ninety_s']
    df['shots_inside_box_per90'] = df['shots_inside_box']/df['ninety_s']
    df['shots_outside_box_per90'] = df['shots_outside_box']/df['ninety_s']
    df['big_chances_missed_per90'] = df['big_chances_missed']/df['ninety_s']
    df['attempt_assists_per90'] = df['attempt_assists']/df['ninety_s']
    df['pass_to_assist_per90'] = df['pass_to_assist']/df['ninety_s']
    df['passes_per90'] = df['passes_total']/df['ninety_s']
    df['passes_final_third_per90'] = df['passes_final_third']/df['ninety_s']
    df['passes_opp_half_per90'] = df['passes_opp_half']/df['ninety_s']
    df['long_balls_per90'] = df['long_balls_total']/df['ninety_s']
    df['crosses_per90'] = df['crosses_total']/df['ninety_s']
    df['chipped_passes_per90'] = df['chipped_passes_total']/df['ninety_s']
    df['touches_per90'] = df['touches']/df['ninety_s']
    df['dispossessed_per90'] = df['dispossessed']/df['ninety_s']
    df['possession_lost_per90'] = df['possession_lost']/df['ninety_s']
    df['ball_recoveries_per90'] = df['ball_recoveries']/df['ninety_s']
    df['possession_won_att_third_per90'] = df['possession_won_att_third']/df['ninety_s']
    df['tackles_per90'] = df['tackles']/df['ninety_s']
    df['clearances_per90'] = df['clearances']/df['ninety_s']
    df['blocked_shots_per90'] = df['blocked_shots']/df['ninety_s']
    df['dribbled_past_per90'] = df['dribbled_past']/df['ninety_s']
    df['fouls_per90'] = df['fouls']/df['ninety_s']
    df['fouled_per90'] = df['fouled']/df['ninety_s']
    # df['player_norm'] = df['_name_norm']
    df['player_norm'] = df['player'].apply(unidecode)

    df.to_csv(f"{filename_full}.csv", index=False, header=True)
    df_reduced = df[['player', 'player_norm', 'team', 'pos', 'games', 'minutes', 'ninety_s', 'shots_per90', 'shots_on_target_per90', 'shots_inside_box_per90', 'shots_outside_box_per90', 'npxg_per90', 'npxg_overperformance', 'goal_conversion_pct', 'big_chances_missed_per90', 'key_passes_per90', 'xag_per90', 'attempt_assists_per90', 'big_chances_created_per90', 'xg_chain_per90', 'xg_buildup_per90', 'pass_to_assist_per90', 'passes_per90', 'pass_completion_pct', 'passes_final_third_per90', 'passes_opp_half_per90', 'long_balls_per90', 'long_balls_pct', 'crosses_per90', 'crosses_pct', 'chipped_passes_per90', 'chipped_passes_pct', 'touches_per90', 'dribbles_per90', 'dribbles_pct', 'dispossessed_per90', 'possession_lost_per90', 'ball_recoveries_per90', 'possession_won_att_third_per90', 'tackles_per90', 'tackles_won_pct', 'interceptions_per90', 'clearances_per90', 'blocked_shots_per90', 'dribbled_past_per90', 'aerials_won_pct', 'ground_duels_won_pct', 'duels_won_pct', 'fouls_per90', 'fouled_per90']]
    df_reduced.to_csv(f"{filename_reduced}.csv", index=False, header=True)

In [5]:
def build_df(filename='stats_reduced', minutes=1500):

    df = pd.read_csv('stats_reduced.csv')
    df_min = df.loc[df['minutes'] >= minutes]
    df_min = df_min.loc[(df['pos'] != 'GK') & (df['pos'] != 'GK S')]
    df_min = df_min.dropna(subset=['pos'])
    df_min = df_min.reset_index()
    df_min = df_min.drop(columns=['index'])
    df_min['goal_conversion_pct'] = df_min['goal_conversion_pct']/100
    df_min['pass_completion_pct'] = df_min['pass_completion_pct']/100
    df_min['long_balls_pct'] = df_min['long_balls_pct']/100
    df_min['crosses_pct'] = df_min['crosses_pct']/100
    df_min['chipped_passes_pct'] = df_min['chipped_passes_pct']/100
    df_min['dribbles_pct'] = df_min['dribbles_pct']/100
    df_min['tackles_won_pct'] = df_min['tackles_won_pct']/100
    df_min['aerials_won_pct'] = df_min['aerials_won_pct']/100
    df_min['ground_duels_won_pct'] = df_min['ground_duels_won_pct']/100
    df_min['duels_won_pct'] = df_min['duels_won_pct']/100


    return df_min

In [6]:
def standardize_df(df):
    scaler = preprocessing.StandardScaler()
    data_df = df.drop(columns=['player', 'player_norm', 'team', 'pos', 'minutes', 'ninety_s', 'games'])
    standard_df = scaler.fit_transform(data_df)
    standard_df = pd.DataFrame(standard_df, columns=data_df.columns)
    standard_df.insert(0, 'player', df['player'])
    standard_df.insert(0, 'player_norm', df['player_norm'])
    standard_df.insert(2, 'team', df['team'])
    standard_df.insert(3, 'pos', df['pos'])
    standard_df.insert(4, 'minutes', df['minutes'])
    standard_df.insert(5, 'ninety_s', df['ninety_s'])
    standard_df.insert(6, 'games', df['games'])
    return standard_df

In [7]:
def apply_pca(df_standard):
    df_pca = df_standard.drop(columns=['player', 'player_norm', 'team', 'pos', 'minutes', 'ninety_s', 'games'])
    pca = PCA(n_components=7)
    data_pca = pca.fit_transform(df_pca)
    data_pca = pd.DataFrame(data_pca)
    data_pca.insert(0, 'player', df_standard['player'])
    data_pca.insert(1, 'player_norm', df_standard['player_norm'])
    data_pca.insert(2, 'team', df_standard['team'])
    data_pca.insert(3, 'pos', df_standard['pos'])
    data_pca.insert(4, 'minutes', df_standard['minutes'])
    data_pca.insert(5, 'ninety_s', df_standard['ninety_s'])
    data_pca.insert(6, 'games', df_standard['games'])

    cont_df = pd.DataFrame()
    feature_names = df_pca.columns
    cont0 = []
    cont1 = []
    cont2 = []
    cont3 = []
    cont4 = []
    cont5 = []
    cont6 = []
    loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
    for i in range(len(feature_names)):
        # print(f"Feature: {feature_names[i]}, Loadings: {loadings[i]}")
        cont0.append(loadings[i][0])
        cont1.append(loadings[i][1])
        cont2.append(loadings[i][2])
        cont3.append(loadings[i][3])
        cont4.append(loadings[i][4])
        cont5.append(loadings[i][5])
        cont6.append(loadings[i][6])
    cont_df['feature'] = feature_names
    cont_df['cont_0'] = cont0
    cont_df['cont_1'] = cont1
    cont_df['cont_2'] = cont2
    cont_df['cont_3'] = cont3
    cont_df['cont_4'] = cont4
    cont_df['cont_5'] = cont5
    cont_df['cont_6'] = cont6
    print(f"PCA Explained Variance: {pca.explained_variance_}")
    return data_pca, cont_df

In [11]:
def get_distances(player_name, df_pca):
    search_row = df_pca.loc[df_pca['player_norm'] == player_name]
    dist_df = pd.DataFrame()
    players = []
    distances = []
    teams = []
    positions = []
    for i in tqdm(df_pca.index, "Computing distances"):
        compare_row = df_pca.loc[i]
        search_player = search_row['player_norm']
        compare_player = compare_row['player_norm']
        compare_team = compare_row['team']
        compare_pos = compare_row['pos']
        search_data = search_row[[0, 1, 2, 3, 4, 5, 6]].to_numpy(dtype=float)
        compare_data = compare_row[[0, 1, 2, 3, 4, 5, 6]].to_numpy(dtype=float)
        distance = np.linalg.norm(search_data - compare_data)
        # print(f"Distance between {search_player} and {compare_player}: {distance}")
        players.append(compare_player)
        distances.append(distance)
        teams.append(compare_team)
        positions.append(compare_pos)
    dist_df['player'] = players
    dist_df['team'] = teams
    dist_df['position'] = positions
    dist_df['distance'] = distances
    dist_df = dist_df.sort_values(by=['distance'], ascending=True)
    return dist_df

In [10]:
build_stats()
df = build_df(minutes=1000)
df_standard = standardize_df(df)
df_pca, cont_df = apply_pca(df_standard)
df_pca

C:\Users\andre\AppData\Local\Temp\ipykernel_5056\2574611101.py:2: DtypeWarning: Columns (0: pos) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('unified_player_stats.csv')

PCA Explained Variance: [12.44265149  8.81167233  2.9988428   2.62378813  1.63459999  1.45000281
  1.16113103]

,player,player_norm,team,pos,minutes,ninety_s,games,0,1,2,3,4,5,6
0,Alejandro Jiménez,Alejandro Jimenez,"AC Milan,Bournemouth",D M S,2396,26.62,32,1.373132,4.201344,-2.605121,1.332206,1.798959,0.508756,-0.088998
1,Samuel Chukwueze,Samuel Chukwueze,"AC Milan,Fulham",M S,1075,11.94,24,7.751837,1.428425,0.214817,0.729325,-0.460624,0.762184,0.922054
2,Adrien Rabiot,Adrien Rabiot,"AC Milan,Marseille",M S,2636,29.29,30,3.229676,3.827653,-0.499775,-1.033977,1.068572,0.718530,1.250521
3,Niclas Füllkrug,Niclas Fullkrug,"AC Milan,West Ham",F S,1042,11.58,28,14.802783,1.785353,-6.251178,-5.927725,-3.209586,0.617340,-1.154595
4,Piero Hincapié,Piero Hincapie,"Arsenal,Bayer Leverkusen",D S,1876,20.84,26,1.869278,10.945856,-1.782080,-2.734567,-1.583713,-1.696780,0.926567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,Renato Veiga,Renato Veiga,Villarreal,D S,2553,28.37,33,-4.256530,-0.571222,0.200602,-0.249285,-0.210134,-2.489483,-0.964230
1419,Santiago Comesaña,Santiago Comesana,Villarreal,M S,2428,26.98,34,-0.494813,-0.603271,0.761722,-0.602802,0.607158,-1.265940,-1.434354
1420,Santiago Mouriño,Santiago Mourino,Villarreal,D S,2485,27.61,29,-3.017562,1.433010,-1.203979,0.112362,0.670659,-0.151637,-0.388417
1421,Sergi Cardona,Sergi Cardona,Villarreal,D S,2028,22.53,32,-0.491831,2.096528,-0.253451,1.435745,-1.568276,-0.624192,-0.167397
1422,Tajon Buchanan,Tajon Buchanan,Villarreal,F M S,1873,20.81,35,0.227755,-2.296423,0.090758,1.841839,0.715615,-1.007663,4.073480

In [65]:
cont_df

,feature,cont_0,cont_1,cont_2,cont_3,cont_4,cont_5,cont_6
0,shots_per90,0.809656,-0.321439,0.194840,0.186274,-0.104803,0.046997,0.001526
1,shots_on_target_per90,0.839117,-0.139419,0.149606,0.359615,-0.162762,0.047047,0.095547
2,shots_inside_box_per90,0.764283,-0.253042,0.136554,0.467813,-0.205238,0.021480,0.027620
3,shots_outside_box_per90,0.721013,0.294872,-0.053684,0.044881,0.049405,0.180592,0.003821
4,npxg_per90,0.688797,-0.448595,0.269226,0.340041,-0.171907,-0.070301,-0.007608
5,npxg_overperformance,-0.091867,0.197951,0.051137,-0.249915,0.176760,-0.033154,0.790782
6,goal_conversion_pct,0.299742,-0.176274,0.332872,0.127063,-0.042013,-0.232221,0.627665
7,big_chances_missed_per90,0.647927,-0.310938,0.165563,0.466389,-0.233033,-0.060243,-0.092363
8,key_passes_per90,0.717097,0.175817,0.044220,-0.524658,-0.061016,0.002073,-0.053936
9,xag_per90,0.717611,0.122967,0.084368,-0.490117,-0.156345,0.022893,-0.035975
10,attempt_assists_per90,0.785981,0.438156,-0.072836,-0.221030,-0.121426,0.039440,-0.024753
11,big_chances_created_per90,0.743622,0.308543,-0.027624,-0.213443,-0.249475,0.061599,-0.006672
12,xg_chain_per90,0.686617,0.034946,0.537759,-0.118964,-0.121975,-0.157254,-0.058435
13,xg_buildup_per90,0.035585,0.489859,0.582073,-0.294972,-0.011027,-0.192518,-0.077170
14,pass_to_assist_per90,0.311439,0.207860,0.059540,-0.205241,-0.147058,0.066826,0.138151
15,passes_per90,-0.190838,0.868345,0.254220,0.165487,-0.099978,-0.177008,-0.021089
16,pass_completion_pct,-0.397168,0.474308,0.478802,-0.108399,0.262670,0.135879,-0.025488
17,passes_final_third_per90,0.510605,0.745340,0.192059,-0.096228,0.041552,-0.101287,-0.046850
18,passes_opp_half_per90,0.219446,0.864843,0.284993,-0.003012,0.025904,-0.151729,-0.037423
19,long_balls_per90,-0.440370,0.671608,-0.008057,0.161384,-0.314014,-0.116129,-0.002239
20,long_balls_pct,0.333931,0.123640,0.544035,0.088250,0.465166,0.060671,-0.091430
21,crosses_per90,0.484293,0.379782,-0.339290,-0.471131,-0.221498,0.111340,0.002839
22,crosses_pct,0.020011,0.180572,-0.048090,-0.144267,0.014556,0.146675,0.146592
23,chipped_passes_per90,-0.136293,0.783489,0.002555,0.050676,-0.287712,-0.149407,-0.036216
24,chipped_passes_pct,0.181652,0.180486,0.475591,0.128991,0.508109,0.042643,-0.093371
25,touches_per90,-0.046467,0.924007,0.098214,0.174430,-0.135316,-0.120457,-0.003779
26,dribbles_per90,0.693597,0.212076,-0.114830,0.014934,0.081557,0.386408,0.038694
27,dribbles_pct,-0.280778,0.274682,0.222760,0.104273,-0.025738,0.416428,-0.103108
28,dispossessed_per90,0.821941,0.003387,-0.175196,0.170694,0.199735,0.107970,0.002951
29,possession_lost_per90,0.629466,0.502905,-0.420338,0.044694,-0.236065,0.018805,0.029805
30,ball_recoveries_per90,0.126700,0.838793,-0.176457,0.188760,0.158577,-0.032089,0.001067
31,possession_won_att_third_per90,0.832100,0.239142,-0.071429,0.100352,0.164060,0.004396,0.010700
32,tackles_per90,-0.095341,0.692074,-0.382947,0.155534,0.250165,-0.058560,-0.000876
33,tackles_won_pct,-0.020808,0.081509,0.000401,0.047424,-0.083442,0.216817,0.170525
34,interceptions_per90,-0.464390,0.596009,-0.140068,0.251969,0.008939,-0.008609,0.062700
35,clearances_per90,-0.720274,0.199014,0.004527,0.314692,-0.359945,0.003872,0.048049
36,blocked_shots_per90,0.838289,0.054312,0.024545,0.214543,-0.063072,0.169843,-0.004030
37,dribbled_past_per90,0.286199,0.576147,-0.415699,0.038588,0.256211,-0.200982,-0.050975
38,aerials_won_pct,-0.557823,0.200112,0.178972,0.378131,-0.232715,0.026388,0.030191
39,ground_duels_won_pct,-0.576033,0.393536,0.165992,-0.005054,-0.067093,0.545243,0.040479
40,duels_won_pct,-0.656589,0.393380,0.220526,0.154085,-0.162922,0.435221,0.066199
41,fouls_per90,0.257028,0.267986,-0.360781,0.531670,0.287323,-0.238269,0.041975
42,fouled_per90,0.567642,0.217268,-0.206792,0.287712,0.181348,0.369591,0.105918

In [12]:
player_name = "Federico Dimarco"
get_distances(player_name, df_pca)

Computing distances: 100%|██████████| 1423/1423 [00:01<00:00, 1299.78it/s]

               player                               team position   distance
955  Federico Dimarco                              Inter      D S   0.000000
242   Bruno Fernandes                  Manchester United        M   2.513808
614     Alex Grimaldo                   Bayer Leverkusen        D   2.813709
403   Florian Thauvin                               Lens      M S   2.856423
233     Mathis Cherki                    Manchester City    F M S   3.022053
..                ...                                ...      ...        ...
6     Ademola Lookman           Atalanta,Atletico Madrid    F M S  17.344165
41        Angel Gomes  Marseille,Wolverhampton Wanderers      M S  17.625627
45        Xavi Simons   RasenBallsport Leipzig,Tottenham    F M S  18.442119
13      Diego Coppola                  Brighton,Paris FC        D  21.929625
8     Conor Gallagher          Atletico Madrid,Tottenham      M S  22.442912

[1423 rows x 4 columns]